"""Added the heading column and removed the status column in the code_submissions table

Revision ID: d7e2d8d626bf
Revises: 
Create Date: 2026-01-03 11:50:05.905321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7e2d8d626bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_submissions', sa.Column('heading', sa.String(), nullable=True))
    op.drop_column('code_submissions', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_submissions', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True))
    op.drop_column('code_submissions', 'heading')
    # ### end Alembic commands ###
